m_manager_m_control_homepage:
    path:     /
    defaults: { _controller: MManagerMControlBundle:Page:index }
    requirements:
            _method: GET

MManagerMControlBundle_homepage:
    path:     /
    defaults: { _controller: MManagerMControlBundle:Page:index }
    requirements:
            _method: GET
            
MManagerMControlBundle_modemformview:
    path:     /modemsaddform/
    defaults: { _controller: MManagerMControlBundle:Page:modemFormView }
    requirements:
            _method: GET|POST
            
MManagerMControlBundle_main:
    path:     /
    defaults: { _controller: MManagerMControlBundle:Page:index }
    requirements:
            _method: GET
            
MManagerMControlBundle_modem_show:
    pattern:  /{id}
    defaults: { _controller: MManagerMControlBundle:modem:show }
    requirements:
        _method:  GET
        id: \d+
        
MManagerMControlBundle_modem_showAll:
    pattern:  /modemlist/
    defaults: { _controller: MManagerMControlBundle:modem:showAll }
    requirements:
        _method:  GET